version: "3.9"
services:
  wordpress:
    image: wordpress
    container_name: wordpress
    ports:
      - "9090:80"
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: admin123
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - reverse_proxy_net

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: wordpress
    volumes:
      - db:/var/lib/mysql
    networks:
      - reverse_proxy_net
    
  nginx:
     image: nginx
     container_name: nginx
     ports:
       - "80:80"
     volumes:
       - nginx_html:/usr/share/nginx/html
     networks:
       - reverse_proxy_net

  flask-app:
    image: tiangolo/uwsgi-nginx-flask:python3.9
    container_name: flask-app
    ports:
      - "5001:80"
    volumes:
      - flask:/app
    networks:
      - reverse_proxy_net

  nodejs-app:
    image: bitnami/node:latest
    container_name: nodejs-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app
    command: ["node", "script.js"]

    networks:
      - reverse_proxy_net


volumes:
  db:
  wordpress:
  nginx_html:
  app:
  flask:
  nodejs:

networks:
  reverse_proxy_net:
    external: true