version: '3.9'
services:
  reverse-proxy:
    image: nginx:latest
    container_name: reverse-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"
    networks:
      - reverse_proxy_net

networks:
  reverse_proxy_net:
    external: true
